name: Build & Deploy to cPanel (FTPS)

on:
  push:
    branches: [ main ]   # adjust if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build (Astro -> dist/)
        run: npm run build

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}          # ftp.enalia-therapy.gr
          username: ${{ secrets.FTP_USERNAME }}    # deploy@enalia-therapy.gr
          password: ${{ secrets.FTP_PASSWORD }}    # Enalia2025!
          port: ${{ secrets.FTP_PORT }}            # 21
          protocol: ftps                           # explicit TLS
          local-dir: dist/
          server-dir: public_html/                 # or your exact document root
          timeout: 600
          # uncomment if you want the action to delete remote files not in dist/
          # dangerous-clean-slate: true
