name: Build & Deploy (FTPS)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build

      - name: Deploy via FTPS (explicit)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 185.25.23.211            # ← χρησιμοποίησε την IP
          username: ${{ secrets.FTP_USERNAME }}   # π.χ. en627321
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps                   # αν κολλήσει, δοκίμασε ftps-legacy
          local-dir: dist/
          server-dir: public_html/
          timeout: 1200
          log-level: verbose
